version: '3.8'

services:
  backend:
    build:
       context: ./backend 
       dockerfile: ./../Dockerfile.backend
    env_file:
      - ./backend/.env
    environment:
      POSTGRES_PASSWORD: postgres  # <--- la usará Python si está en la .env con variable `${POSTGRES_PASSWORD}`
    ports:
      - "5000:5000"
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend/remote-medic
      dockerfile: ../../Dockerfile.frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: app_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  pgdata:
