FROM node:20-alpine

WORKDIR /app

# Copiar package.json y lock desde el contexto correcto
COPY . .

RUN npm install -g pnpm

RUN pnpm install

RUN npm run build

RUN npm install -g serve

CMD ["serve", "-s", "dist", "-l", "5173"]
